import type { MaintenanceTemplate } from './types';

const templates: MaintenanceTemplate[] = [
  {
    id: 'engine-oil',
    title: 'Моторное масло',
    intervalDistance: 10000,
    intervalMonths: 12,
    notes: 'Менять фильтр при каждой замене. Синтетика предпочтительна.',
    sourceUrl: 'https://www.startmycar.com/gb/nissan/note/guides/when-to-change-motor-oil',
    unitDistance: 'km',
  },
  {
    id: 'oil-filter',
    title: 'Масляный фильтр',
    intervalDistance: 10000,
    intervalMonths: 12,
    notes: 'Каждую замену масла.',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/filters',
    unitDistance: 'km',
  },
  {
    id: 'air-filter',
    title: 'Воздушный фильтр',
    intervalDistance: 11000,
    notes: 'Чаще при пыли/грунтовках.',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/filters',
    unitDistance: 'km',
  },
  {
    id: 'fuel-filter-gas',
    title: 'Топливный фильтр (бензин)',
    intervalDistance: 16000,
    intervalMonths: 12,
    notes: 'Качество топлива критично.',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/filters',
    unitDistance: 'km',
  },
  {
    id: 'fuel-filter-diesel',
    title: 'Топливный фильтр (дизель)',
    intervalDistance: 50000,
    unitDistance: 'km',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/filters',
  },
  {
    id: 'cabin-filter',
    title: 'Салонный фильтр',
    intervalDistance: 15000,
    intervalMonths: 12,
    notes: '10–30 тыс. км в зависимости от среды.',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/filters',
    unitDistance: 'km',
  },
  {
    id: 'spark-plugs',
    title: 'Свечи зажигания',
    intervalDistance: 60000,
    notes: 'Тип по мануалу; иридий/платина живут дольше.',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/what-spark-plugs-to-use',
    unitDistance: 'km',
  },
  {
    id: 'serpentine-belt',
    title: 'Приводной ремень',
    intervalDistance: 40000,
    notes: 'Проверка с 40k, далее при каждом ТО.',
    sourceUrl: 'https://www.startmycar.com/nissan/note/guides/serpentine-belt',
    unitDistance: 'km',
  },
  {
    id: 'brake-fluid',
    title: 'Тормозная жидкость',
    intervalMonths: 24,
    notes: 'DOT по крышке бачка. Не смешивать.',
    sourceUrl: 'https://www.startmycar.com/gb/nissan/note/guides/brake-fluid',
    unitDistance: 'km',
  },
  {
    id: 'atf',
    title: 'Жидкость АКПП/вариатора',
    intervalDistance: 40000,
    notes: 'Только рекомендованный тип (Nissan Matic / NS-2/NS-3).',
    sourceUrl: 'https://www.startmycar.com/nissan/note/guides/transmission-fluid-change',
    unitDistance: 'km',
  },
  {
    id: 'mt-oil',
    title: 'Масло МКПП',
    intervalDistance: 80000,
    sourceUrl: 'https://www.startmycar.com/gb/nissan/note/guides/what-transmission-fluid-to-use',
    unitDistance: 'km',
  },
  {
    id: 'coolant',
    title: 'Охлаждающая жидкость',
    intervalMonths: 36,
    notes: 'Лонг-лайф антифриз, тип по мануалу. Не мешать цвета/типы.',
    sourceUrl: 'https://www.startmycar.com/nissan/note/guides/overheating',
    unitDistance: 'km',
  },
  {
    id: 'battery',
    title: 'Аккумулятор',
    intervalMonths: 48,
    notes: 'Брать свежий (≤6 мес). Проверка напряжения по гайду.',
    sourceUrl: 'https://www.startmycar.com/gb/nissan/note/guides/how-to-test-the-battery',
    unitDistance: 'km',
  },
  {
    id: 'tires-rotation',
    title: 'Шины (ротация/контроль)',
    intervalDistance: 10000,
    notes: 'Давление по стикеру двери. Ротация и баланс/схождение.',
    sourceUrl: 'https://www.startmycar.com/us/nissan/note/guides/tire-pressure',
    unitDistance: 'km',
  },
];

export default templates;